name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - ipympl
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - satpy
  - imageio
  - imageio-ffmpeg
  - rasterio
  - requests
  - geoviews
  - pip:
    - kubernetes
    - graphviz
