#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             jupyter-matplotlib \
                             dask-labextension

# Replace all `%matplotlib notebook` usage with `%matplotlib widget`
find notebooks -type f -name "*.ipynb" -print0 | xargs -0 sed -i 's/%matplotlib notebook/%matplotlib widget/g'

#EOF
